name: app_physics
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Mantain application state
  shared_preferences: ^0.5.12

  # Library to make http requests
  dio: ^3.0.10
  
  # Google fonts
  google_fonts: ^1.1.0
  
  firebase_messaging: ^7.0.3

  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
